name: flutter_bloc_boilerplate_v2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # Route
  go_router: ^14.3.0

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Dependency injection
  get_it: ^8.0.0

  # Network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.0.5

  # Local storage
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^3.0.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # Localization
  generate: true

  assets:
    - assets/images/
