name: hangman_word_quest
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # common
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^10.1.2
  dartz: ^0.10.1
  get_it: ^7.6.0
  lottie: ^2.6.0
  #share_plus: ^7.1.0
  share_plus: ^6.3.2
  url_launcher: ^6.1.14

  # Network
  http: ^1.1.0
  internet_connection_checker_plus: ^2.0.0

  # Local storage
  shared_preferences: ^2.2.0

  # class base calls
  json_annotation: ^4.8.1

  # firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1

  # social login
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # class base calls
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # Localization
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
