name: rest_api_client
description: "The rest api client that handle all rest api request."
version: 0.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1